### ISSUE TITLE
Test failing in should-pass only when deducing entire directory

### ISSUE THREAD

**Issue by Temperz87** [jsiek/deduce#114]
When I run on my machine
`deduce test/should-pass`
I get the error
```
~/Documents/deduce-development/lib//Nat.pf:105.32-105.51: in call iterate(n, init, f)
	could not deduce a type for T to instantiate iterate
	whose type is: (fn <T> Nat, T, (fn T -> T) -> T)
```
Recall earlier that @mateidragony got a similar error, where when running the tester tests fail. I think this is a symptom of something being wrong with how deduce handles importing modules when working on multiple files, coupled with `os.listdir` returning files in a random order.

You can recreate this behavior by running the following command while inside of `test/should-pass`:

```
$deduce ./suffices_rewrite.pf ./implicit_modus_ponens.pf ./induction1.pf ./switch_term.pf ./theorem_implies4.pf ./theorem_and.pf ./mark2.pf ./generic2.pf ./theorem_and4.pf ./theorem_or2.pf ./array3.pf ./generic-syth.pf ./rewrite_with_all.pf ./definition_in.pf ./theorem_false3.pf ./theorem_implies2.pf ./eval-fact.pf ./inst3.pf ./all2.pf ./theorem_iff.pf ./inst1.pf ./array1.pf ./doc_programming.pf ./rec1.pf ./rewrite_all_mark.pf ./inst2.pf ./theorem_implies3.pf ./function1.pf 
```

Where `$deduce` represents calling `python3 deduce.py` or an alternative.

I've tried to shorten the call, but I think I'd need a script to determine what the smallest amount of calls I give Deduce before it fails would be.

**Comment by jsiek** [comment]
I pushed some changes to `test-deduce.py` but didn't intend to fix this bug...

**Comment by Temperz87** [comment]
The bug is still there, try running the command I posted. I'm 99% sure it's something to do with the order the files are processed in, and the command should enforce that ordering.

**Comment by Temperz87** [comment]
Also, with the changes to the tester and deduce (a defined ordering for processing folders), there if one person is getting a bug everyone should be getting the bug

**Comment by HalflingHelper** [comment]
The command works on my machine btw

**Comment by Temperz87** [comment]
It works on my machine as well...

I even tried renaming the `should-validate` directory back to `should-pass` and it does. I don't know if this means the bug magically fixed itself, or if I can find another ordering that'll cause deduce to break

**Comment by jsiek** [comment]
ok, I'll close this issue
